"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BoundingBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_MIN_FIELD_NUMBER: builtins.int
    Y_MIN_FIELD_NUMBER: builtins.int
    X_MAX_FIELD_NUMBER: builtins.int
    Y_MAX_FIELD_NUMBER: builtins.int
    x_min: builtins.float
    y_min: builtins.float
    x_max: builtins.float
    y_max: builtins.float
    def __init__(
        self,
        *,
        x_min: builtins.float = ...,
        y_min: builtins.float = ...,
        x_max: builtins.float = ...,
        y_max: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x_max", b"x_max", "x_min", b"x_min", "y_max", b"y_max", "y_min", b"y_min"]) -> None: ...

Global___BoundingBox: typing_extensions.TypeAlias = BoundingBox

@typing.final
class Point2D(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y"]) -> None: ...

Global___Point2D: typing_extensions.TypeAlias = Point2D

@typing.final
class Circle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CENTER_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    radius: builtins.float
    @property
    def center(self) -> Global___Point2D: ...
    def __init__(
        self,
        *,
        center: Global___Point2D | None = ...,
        radius: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["center", b"center"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["center", b"center", "radius", b"radius"]) -> None: ...

Global___Circle: typing_extensions.TypeAlias = Circle

@typing.final
class DetectionGeometry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOX_FIELD_NUMBER: builtins.int
    POINT_FIELD_NUMBER: builtins.int
    CIRCLE_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    @property
    def box(self) -> Global___BoundingBox: ...
    @property
    def point(self) -> Global___Point2D: ...
    @property
    def circle(self) -> Global___Circle: ...
    @property
    def custom(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        box: Global___BoundingBox | None = ...,
        point: Global___Point2D | None = ...,
        circle: Global___Circle | None = ...,
        custom: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["box", b"box", "circle", b"circle", "custom", b"custom", "point", b"point", "shape", b"shape"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["box", b"box", "circle", b"circle", "custom", b"custom", "point", b"point", "shape", b"shape"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["shape", b"shape"]) -> typing.Literal["box", "point", "circle", "custom"] | None: ...

Global___DetectionGeometry: typing_extensions.TypeAlias = DetectionGeometry

@typing.final
class Detection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLASS_NAME_FIELD_NUMBER: builtins.int
    CLASS_ID_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    GEOMETRY_FIELD_NUMBER: builtins.int
    NORMALIZED_GEOMETRY_FIELD_NUMBER: builtins.int
    class_name: builtins.str
    class_id: builtins.int
    score: builtins.float
    @property
    def geometry(self) -> Global___DetectionGeometry: ...
    @property
    def normalized_geometry(self) -> Global___DetectionGeometry: ...
    def __init__(
        self,
        *,
        class_name: builtins.str = ...,
        class_id: builtins.int = ...,
        score: builtins.float = ...,
        geometry: Global___DetectionGeometry | None = ...,
        normalized_geometry: Global___DetectionGeometry | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["geometry", b"geometry", "normalized_geometry", b"normalized_geometry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["class_id", b"class_id", "class_name", b"class_name", "geometry", b"geometry", "normalized_geometry", b"normalized_geometry", "score", b"score"]) -> None: ...

Global___Detection: typing_extensions.TypeAlias = Detection

@typing.final
class StreamConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    VIDEO_CODEC_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: builtins.int
    MAX_DETECTIONS_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    video_codec: builtins.str
    """例如 "h264" """
    width: builtins.int
    height: builtins.int
    score_threshold: builtins.float
    max_detections: builtins.int
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        video_codec: builtins.str = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        score_threshold: builtins.float = ...,
        max_detections: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["height", b"height", "max_detections", b"max_detections", "score_threshold", b"score_threshold", "stream_id", b"stream_id", "video_codec", b"video_codec", "width", b"width"]) -> None: ...

Global___StreamConfig: typing_extensions.TypeAlias = StreamConfig
