"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import artemis_cve.protos.detector.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ImageFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    """原始图像字节，例如 RGB/BGR 编码后的连续内存或压缩图像"""
    width: builtins.int
    height: builtins.int
    format: builtins.str
    """例如 "rgb8"、"bgr8"、"jpeg"、"png"、"h264" """
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        format: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "format", b"format", "height", b"height", "width", b"width"]) -> None: ...

Global___ImageFrame: typing_extensions.TypeAlias = ImageFrame

@typing.final
class DetectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: builtins.int
    MAX_DETECTIONS_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    score_threshold: builtins.float
    max_detections: builtins.int
    @property
    def frame(self) -> Global___ImageFrame: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        frame: Global___ImageFrame | None = ...,
        score_threshold: builtins.float = ...,
        max_detections: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["frame", b"frame"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["frame", b"frame", "max_detections", b"max_detections", "request_id", b"request_id", "score_threshold", b"score_threshold"]) -> None: ...

Global___DetectRequest: typing_extensions.TypeAlias = DetectRequest

@typing.final
class DetectReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    DETECTIONS_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def detections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[artemis_cve.protos.detector.common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        detections: collections.abc.Iterable[artemis_cve.protos.detector.common_pb2.Detection] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["detections", b"detections", "request_id", b"request_id"]) -> None: ...

Global___DetectReply: typing_extensions.TypeAlias = DetectReply

@typing.final
class EncodedVideoChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    PTS_MS_FIELD_NUMBER: builtins.int
    DTS_MS_FIELD_NUMBER: builtins.int
    KEY_FRAME_FIELD_NUMBER: builtins.int
    CODEC_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    """编码后的视频载荷，支持 H.264 NALU 或 Annex-B 字节流"""
    pts_ms: builtins.int
    dts_ms: builtins.int
    key_frame: builtins.bool
    codec: builtins.str
    """例如 "h264" """
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        pts_ms: builtins.int = ...,
        dts_ms: builtins.int = ...,
        key_frame: builtins.bool = ...,
        codec: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["codec", b"codec", "data", b"data", "dts_ms", b"dts_ms", "key_frame", b"key_frame", "pts_ms", b"pts_ms"]) -> None: ...

Global___EncodedVideoChunk: typing_extensions.TypeAlias = EncodedVideoChunk

@typing.final
class StreamDetectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    @property
    def config(self) -> artemis_cve.protos.detector.common_pb2.StreamConfig: ...
    @property
    def frame(self) -> Global___ImageFrame: ...
    @property
    def chunk(self) -> Global___EncodedVideoChunk: ...
    def __init__(
        self,
        *,
        config: artemis_cve.protos.detector.common_pb2.StreamConfig | None = ...,
        frame: Global___ImageFrame | None = ...,
        chunk: Global___EncodedVideoChunk | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk", "config", b"config", "frame", b"frame", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chunk", b"chunk", "config", b"config", "frame", b"frame", "payload", b"payload"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["config", "frame", "chunk"] | None: ...

Global___StreamDetectRequest: typing_extensions.TypeAlias = StreamDetectRequest

@typing.final
class StreamDetectReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    PTS_MS_FIELD_NUMBER: builtins.int
    DETECTIONS_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    request_id: builtins.str
    pts_ms: builtins.int
    frame_id: builtins.int
    @property
    def detections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[artemis_cve.protos.detector.common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        request_id: builtins.str = ...,
        pts_ms: builtins.int = ...,
        detections: collections.abc.Iterable[artemis_cve.protos.detector.common_pb2.Detection] | None = ...,
        frame_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["detections", b"detections", "frame_id", b"frame_id", "pts_ms", b"pts_ms", "request_id", b"request_id", "stream_id", b"stream_id"]) -> None: ...

Global___StreamDetectReply: typing_extensions.TypeAlias = StreamDetectReply
