"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import artemis_cve.protos.detector.detector_pb2
import collections.abc
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_DetectorEngineDetectType = typing_extensions.TypeVar(
    '_DetectorEngineDetectType',
    grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.detector_pb2.DetectRequest,
        artemis_cve.protos.detector.detector_pb2.DetectReply,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.detector_pb2.DetectRequest,
        artemis_cve.protos.detector.detector_pb2.DetectReply,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.detector_pb2.DetectRequest,
        artemis_cve.protos.detector.detector_pb2.DetectReply,
    ],
)

_DetectorEngineStreamDetectType = typing_extensions.TypeVar(
    '_DetectorEngineStreamDetectType',
    grpc.StreamStreamMultiCallable[
        artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
        artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
    ],
    grpc.aio.StreamStreamMultiCallable[
        artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
        artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
    ],
    default=grpc.StreamStreamMultiCallable[
        artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
        artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
    ],
)

class DetectorEngineStub(typing.Generic[_DetectorEngineDetectType, _DetectorEngineStreamDetectType]):
    @typing.overload
    def __init__(self: DetectorEngineStub[
        grpc.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.detector_pb2.DetectRequest,
            artemis_cve.protos.detector.detector_pb2.DetectReply,
        ],
        grpc.StreamStreamMultiCallable[
            artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
            artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: DetectorEngineStub[
        grpc.aio.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.detector_pb2.DetectRequest,
            artemis_cve.protos.detector.detector_pb2.DetectReply,
        ],
        grpc.aio.StreamStreamMultiCallable[
            artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
            artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Detect: _DetectorEngineDetectType
    """输入单帧图像，返回该帧中的目标检测结果。"""

    StreamDetect: _DetectorEngineStreamDetectType
    """输入连续视频流，持续返回该流中的目标检测结果。"""

DetectorEngineAsyncStub: typing_extensions.TypeAlias = DetectorEngineStub[
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.detector_pb2.DetectRequest,
        artemis_cve.protos.detector.detector_pb2.DetectReply,
    ],
    grpc.aio.StreamStreamMultiCallable[
        artemis_cve.protos.detector.detector_pb2.StreamDetectRequest,
        artemis_cve.protos.detector.detector_pb2.StreamDetectReply,
    ],
]

class DetectorEngineServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Detect(
        self,
        request: artemis_cve.protos.detector.detector_pb2.DetectRequest,
        context: _ServicerContext,
    ) -> typing.Union[artemis_cve.protos.detector.detector_pb2.DetectReply, collections.abc.Awaitable[artemis_cve.protos.detector.detector_pb2.DetectReply]]:
        """输入单帧图像，返回该帧中的目标检测结果。"""

    @abc.abstractmethod
    def StreamDetect(
        self,
        request_iterator: _MaybeAsyncIterator[artemis_cve.protos.detector.detector_pb2.StreamDetectRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[artemis_cve.protos.detector.detector_pb2.StreamDetectReply], collections.abc.AsyncIterator[artemis_cve.protos.detector.detector_pb2.StreamDetectReply]]:
        """输入连续视频流，持续返回该流中的目标检测结果。"""

def add_DetectorEngineServicer_to_server(servicer: DetectorEngineServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
