"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import artemis_cve.protos.detector.webrtc_detector_pb2
import collections.abc
import grpc
import grpc.aio
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_WebRtcDetectorEngineCreateStreamType = typing_extensions.TypeVar(
    '_WebRtcDetectorEngineCreateStreamType',
    grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
    ],
)

_WebRtcDetectorEngineUpdateStreamType = typing_extensions.TypeVar(
    '_WebRtcDetectorEngineUpdateStreamType',
    grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
        artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
        artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
        artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
    ],
)

_WebRtcDetectorEngineStreamDetectionsType = typing_extensions.TypeVar(
    '_WebRtcDetectorEngineStreamDetectionsType',
    grpc.UnaryStreamMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
    ],
    default=grpc.UnaryStreamMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
    ],
)

class WebRtcDetectorEngineStub(typing.Generic[_WebRtcDetectorEngineCreateStreamType, _WebRtcDetectorEngineUpdateStreamType, _WebRtcDetectorEngineStreamDetectionsType]):
    @typing.overload
    def __init__(self: WebRtcDetectorEngineStub[
        grpc.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
            artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
        ],
        grpc.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
            artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
        ],
        grpc.UnaryStreamMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: WebRtcDetectorEngineStub[
        grpc.aio.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
            artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
            artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
        ],
        grpc.aio.UnaryStreamMultiCallable[
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
            artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    CreateStream: _WebRtcDetectorEngineCreateStreamType
    """创建基于 WebRTC 的流式检测会话。"""

    UpdateStream: _WebRtcDetectorEngineUpdateStreamType
    """客户端提交 WebRTC answer 或后续 ICE candidate。"""

    StreamDetections: _WebRtcDetectorEngineStreamDetectionsType
    """订阅指定流会话的检测结果。"""

WebRtcDetectorEngineAsyncStub: typing_extensions.TypeAlias = WebRtcDetectorEngineStub[
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
        artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
        artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply,
    ],
]

class WebRtcDetectorEngineServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def CreateStream(
        self,
        request: artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamRequest,
        context: _ServicerContext,
    ) -> typing.Union[artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply, collections.abc.Awaitable[artemis_cve.protos.detector.webrtc_detector_pb2.CreateStreamReply]]:
        """创建基于 WebRTC 的流式检测会话。"""

    @abc.abstractmethod
    def UpdateStream(
        self,
        request: artemis_cve.protos.detector.webrtc_detector_pb2.StreamSignal,
        context: _ServicerContext,
    ) -> typing.Union[artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply, collections.abc.Awaitable[artemis_cve.protos.detector.webrtc_detector_pb2.UpdateStreamReply]]:
        """客户端提交 WebRTC answer 或后续 ICE candidate。"""

    @abc.abstractmethod
    def StreamDetections(
        self,
        request: artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply], collections.abc.AsyncIterator[artemis_cve.protos.detector.webrtc_detector_pb2.StreamDetectionsReply]]:
        """订阅指定流会话的检测结果。"""

def add_WebRtcDetectorEngineServicer_to_server(servicer: WebRtcDetectorEngineServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
