"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import artemis_cve.protos.detector.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IceServer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URLS_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    CREDENTIAL_FIELD_NUMBER: builtins.int
    username: builtins.str
    credential: builtins.str
    @property
    def urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        urls: collections.abc.Iterable[builtins.str] | None = ...,
        username: builtins.str = ...,
        credential: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credential", b"credential", "urls", b"urls", "username", b"username"]) -> None: ...

Global___IceServer: typing_extensions.TypeAlias = IceServer

@typing.final
class SessionDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    SDP_FIELD_NUMBER: builtins.int
    type: builtins.str
    """"offer" or "answer" """
    sdp: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        sdp: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sdp", b"sdp", "type", b"type"]) -> None: ...

Global___SessionDescription: typing_extensions.TypeAlias = SessionDescription

@typing.final
class IceCandidate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CANDIDATE_FIELD_NUMBER: builtins.int
    SDP_MID_FIELD_NUMBER: builtins.int
    SDP_MLINE_INDEX_FIELD_NUMBER: builtins.int
    candidate: builtins.str
    sdp_mid: builtins.str
    sdp_mline_index: builtins.int
    def __init__(
        self,
        *,
        candidate: builtins.str = ...,
        sdp_mid: builtins.str = ...,
        sdp_mline_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["candidate", b"candidate", "sdp_mid", b"sdp_mid", "sdp_mline_index", b"sdp_mline_index"]) -> None: ...

Global___IceCandidate: typing_extensions.TypeAlias = IceCandidate

@typing.final
class CreateStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    @property
    def config(self) -> artemis_cve.protos.detector.common_pb2.StreamConfig: ...
    def __init__(
        self,
        *,
        config: artemis_cve.protos.detector.common_pb2.StreamConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config"]) -> None: ...

Global___CreateStreamRequest: typing_extensions.TypeAlias = CreateStreamRequest

@typing.final
class CreateStreamReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    OFFER_FIELD_NUMBER: builtins.int
    ICE_SERVERS_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    @property
    def offer(self) -> Global___SessionDescription: ...
    @property
    def ice_servers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___IceServer]: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        offer: Global___SessionDescription | None = ...,
        ice_servers: collections.abc.Iterable[Global___IceServer] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["offer", b"offer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ice_servers", b"ice_servers", "offer", b"offer", "stream_id", b"stream_id"]) -> None: ...

Global___CreateStreamReply: typing_extensions.TypeAlias = CreateStreamReply

@typing.final
class StreamSignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    ANSWER_FIELD_NUMBER: builtins.int
    ICE_CANDIDATE_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    @property
    def answer(self) -> Global___SessionDescription: ...
    @property
    def ice_candidate(self) -> Global___IceCandidate: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        answer: Global___SessionDescription | None = ...,
        ice_candidate: Global___IceCandidate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["answer", b"answer", "ice_candidate", b"ice_candidate", "signal", b"signal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["answer", b"answer", "ice_candidate", b"ice_candidate", "signal", b"signal", "stream_id", b"stream_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["signal", b"signal"]) -> typing.Literal["answer", "ice_candidate"] | None: ...

Global___StreamSignal: typing_extensions.TypeAlias = StreamSignal

@typing.final
class UpdateStreamReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICE_CANDIDATES_FIELD_NUMBER: builtins.int
    @property
    def ice_candidates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___IceCandidate]: ...
    def __init__(
        self,
        *,
        ice_candidates: collections.abc.Iterable[Global___IceCandidate] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ice_candidates", b"ice_candidates"]) -> None: ...

Global___UpdateStreamReply: typing_extensions.TypeAlias = UpdateStreamReply

@typing.final
class StreamDetectionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stream_id", b"stream_id"]) -> None: ...

Global___StreamDetectionsRequest: typing_extensions.TypeAlias = StreamDetectionsRequest

@typing.final
class StreamDetectionsReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    PTS_MS_FIELD_NUMBER: builtins.int
    DETECTIONS_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    request_id: builtins.str
    pts_ms: builtins.int
    frame_id: builtins.int
    @property
    def detections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[artemis_cve.protos.detector.common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        request_id: builtins.str = ...,
        pts_ms: builtins.int = ...,
        detections: collections.abc.Iterable[artemis_cve.protos.detector.common_pb2.Detection] | None = ...,
        frame_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["detections", b"detections", "frame_id", b"frame_id", "pts_ms", b"pts_ms", "request_id", b"request_id", "stream_id", b"stream_id"]) -> None: ...

Global___StreamDetectionsReply: typing_extensions.TypeAlias = StreamDetectionsReply
